-- 001_directory.sql
-- 봇 Postgres: 멤버 디렉터리 + PR 스레드 스키마 (인터널 MySQL → Postgres 이관)
-- 출처: 라즈베리파이 bcsd-mysql / bcsdlab (backup/bcsdlab_*.sql)
-- 방침: 기능명세서 B-1 / B-1.1
--
-- 타입 매핑: tinyint(1)→boolean, datetime→timestamptz, enum→varchar+CHECK,
--            AUTO_INCREMENT→GENERATED BY DEFAULT AS IDENTITY(시드 시 기존 id 보존 후 setval)
-- 제외: member.password (자격증명 — 아카이브 덤프에만 보존)
-- 생성 순서: track → team → member → team_map → member_withdraw → pr_thread (FK 의존)

-- updated_at 자동 갱신 (MySQL의 ON UPDATE CURRENT_TIMESTAMP 대체)
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ── track ────────────────────────────────────────────────
CREATE TABLE track (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       varchar(255) NOT NULL UNIQUE,
  is_deleted boolean      NOT NULL DEFAULT false,
  created_at timestamptz  DEFAULT now(),
  updated_at timestamptz  DEFAULT now()
);

-- ── team ─────────────────────────────────────────────────
CREATE TABLE team (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       varchar(30),
  is_deleted boolean,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ── member ───────────────────────────────────────────────
CREATE TABLE member (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              varchar(255) NOT NULL,
  slack_id          varchar(255),
  github_name       varchar(255),
  member_type       varchar(20)  CHECK (member_type IN ('BEGINNER','REGULAR','MENTOR')),
  track_id          bigint       REFERENCES track(id),
  status            varchar(20)  CHECK (status IN ('ATTEND','OFF','IPP','ARMY','COMPLETION','GRADUATE')),
  authority         varchar(20)  CHECK (authority IN ('NORMAL','MANAGER','ADMIN')),
  is_active         boolean      NOT NULL DEFAULT true,
  is_deleted        boolean      DEFAULT false,
  is_authed         boolean,
  is_fee_exempt     boolean,
  company           varchar(255),
  department        varchar(255),
  student_number    varchar(255) UNIQUE,
  email             varchar(255) UNIQUE,
  phone_number      varchar(255),
  birthday          date,
  profile_image_url varchar(512),
  join_date         date,
  created_at        timestamptz  DEFAULT now(),
  updated_at        timestamptz  DEFAULT now()
);
CREATE INDEX idx_member_slack_id    ON member(slack_id)    WHERE slack_id IS NOT NULL;
CREATE INDEX idx_member_github_name ON member(github_name) WHERE github_name IS NOT NULL;
CREATE INDEX idx_member_active      ON member(is_active);

-- ── team_map (멤버 ↔ 팀, 다대다) ─────────────────────────
CREATE TABLE team_map (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id  bigint REFERENCES member(id) ON DELETE CASCADE,
  team_id    bigint REFERENCES team(id)   ON DELETE CASCADE,
  is_leader  boolean,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX idx_team_map_member ON team_map(member_id);
CREATE INDEX idx_team_map_team   ON team_map(team_id);

-- ── member_withdraw (탈퇴 기록) ──────────────────────────
CREATE TABLE member_withdraw (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id     bigint REFERENCES member(id) ON DELETE CASCADE,
  reason        text,
  withdraw_date timestamptz,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now()
);

-- ── pr_thread (← thread; PR 리뷰 스레드 추적) ────────────
-- reminder_sent 제외: stale PR 리마인더는 GitHub 네이티브가 담당
CREATE TABLE pr_thread (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pr_link    varchar(512),
  ts         varchar(255),  -- 연결된 Slack 메시지 timestamp
  reviewer   varchar(255),
  writer     varchar(255),
  status     varchar(20) DEFAULT 'open' CHECK (status IN ('open','merged','closed')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX idx_pr_thread_pr_link ON pr_thread(pr_link);

-- updated_at 트리거 부착
CREATE TRIGGER trg_track_updated           BEFORE UPDATE ON track           FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_team_updated            BEFORE UPDATE ON team            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_member_updated          BEFORE UPDATE ON member          FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_team_map_updated        BEFORE UPDATE ON team_map        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_member_withdraw_updated BEFORE UPDATE ON member_withdraw FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_pr_thread_updated       BEFORE UPDATE ON pr_thread       FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 시드(데이터 적재) 이후 실행할 것:
--  1) IDENTITY 시퀀스를 기존 최대 id 다음으로 맞춤:
--     SELECT setval(pg_get_serial_sequence('member','id'),   (SELECT COALESCE(MAX(id),1) FROM member));
--     (track/team/team_map/member_withdraw/pr_thread 동일)
--  2) 시드 정정(기능명세 B-2): member 2357 is_active=0, 본인 authority='ADMIN'
