-- 002_rag.sql
-- RAG(지식 검색) 스키마: 문서 청크 임베딩 + 동기화 커서
-- 전제: CREATE EXTENSION vector (pgvector) 적용됨. bge-m3 임베딩 = 1024차원.

-- 지식 소스 문서 청크 (청킹 → bge-m3 임베딩 → 벡터검색)
CREATE TABLE document_chunk (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source         varchar(50) NOT NULL,   -- 'github' | 'notion' | 'drive' | 'manual'
  source_url     text,                   -- 원본 링크(출처 병기용)
  project        varchar(100),           -- 스코프(코인/bcsd/공통 등)
  title          text,
  content        text NOT NULL,          -- 청크 본문
  embedding      vector(1024) NOT NULL,  -- bge-m3
  last_synced_at timestamptz DEFAULT now()
);
-- ANN 인덱스 (코사인 유사도)
CREATE INDEX idx_document_chunk_embedding ON document_chunk
  USING hnsw (embedding vector_cosine_ops);
CREATE INDEX idx_document_chunk_source  ON document_chunk(source);
CREATE INDEX idx_document_chunk_project ON document_chunk(project);

-- 커넥터별 증분 동기화 커서
CREATE TABLE sync_cursor (
  connector      varchar(50) PRIMARY KEY,  -- 'github' | 'notion' | 'drive'
  last_edited_at timestamptz,
  updated_at     timestamptz DEFAULT now()
);
