-- 005_query_log.sql
-- RAG 질의 로그: 실사용량·응답시간·해결률(found)·만족도(feedback) 측정용.
-- PII 비저장 — user는 sha256 해시 앞 16자만 저장(동일인 식별만 가능, 원본 Slack ID 미보관).

CREATE TABLE rag_query_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel     text NOT NULL,
  msg_ts      text NOT NULL,             -- 답변 메시지 ts (👍/👎 피드백 매칭용)
  user_hash   text NOT NULL,            -- sha256(userId)[:16] — PII 아님
  question    text NOT NULL,
  answer      text,                      -- 봇이 생성한 답변 본문(👎 원인 분석용)
  found       boolean NOT NULL,          -- 출처를 찾았나(false = 코퍼스 빈틈 신호)
  source_urls text[],                    -- 답변에 쓰인 top 출처 URL
  latency_ms  integer,                   -- 검색+생성 총 소요(ms)
  feedback    smallint,                  -- +1 / -1 / NULL (reaction_added로 채움)
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_rag_query_log_msg_ts  ON rag_query_log(msg_ts);
CREATE INDEX idx_rag_query_log_created ON rag_query_log(created_at);
